// Breaks "BitD Crew Token Action Maker.js" in many small ways, one at a time, and checks that crew_mock_test.js fails each time.
// Usage: node crew_mutation_check.js <crew script> <translation.json> <PC script>
// A mutation that is not applied (its text is missing or ambiguous) or that survives (tests still pass) is a failure.
const fs = require('fs');
const os = require('os');
const path = require('path');
const cp = require('child_process');

const SCRIPT = process.argv[2], TRANS = process.argv[3], PC = process.argv[4];
if (!SCRIPT || !TRANS || !PC) { console.log('usage: node crew_mutation_check.js <crew script> <translation.json> <PC script>'); process.exit(2); }
const SRC = fs.readFileSync(SCRIPT, 'utf8');
const TEST = path.join(__dirname, 'crew_mock_test.js');

const M = [
  ['Heat track of 10', "var HEAT_MAX = 9, REP_MAX = 12", "var HEAT_MAX = 10, REP_MAX = 12"],
  ['Heat fills at 10 not 9', "while (total >= HEAT_MAX) {", "while (total > HEAT_MAX) {"],
  ['Wanted not capped', "if (wanted < w.max) { wanted++; } else { capped++; }", "wanted++;"],
  ['crew Tier left out of score Heat', "var total = base + tier + target1 + chaos + death + wit,", "var total = base + target1 + chaos + death + wit,"],
  ['Rep 1 per 3 Heat', "Math.floor(total / 2) + Math.max(0, tTier - tier)", "Math.floor(total / 3) + Math.max(0, tTier - tier)"],
  ['payoff 2 x target Tier', "var payoff = pcs + 3 * tTier;", "var payoff = pcs + 2 * tTier;"],
  ['tithe 1 per 5', "flow.tier <= 2 ? Math.floor(flow.earned / 4) : 0", "flow.tier <= 2 ? Math.floor(flow.earned / 5) : 0"],
  ['tithe up to Tier 3', "flow.tier <= 2 ? Math.floor(flow.earned / 4) : 0", "flow.tier <= 3 ? Math.floor(flow.earned / 4) : 0"],
  ['crew gate points at characters', "getAttr(ch.id, 'sheet_type', 'character') !== 'crew'", "getAttr(ch.id, 'sheet_type', 'character') !== 'character'"],
  ['crew auto rule fires on any sheet', "if (!ch || getAttr(cid, 'sheet_type', 'character') !== 'crew') { return; }", "if (!ch) { return; }"],
  ['anyone may use any crew', "return cb.indexOf('all') >= 0 || cb.indexOf(msg.playerid) >= 0;", "return true;"],
  ['command shared with the PC script', "var CMD = '!bitdcrew';", "var CMD = '!bitd';"],
  ['ability marker shared with the PC script', "var MARK = 'bitd-crew-tam';", "var MARK = 'bitd-tam';"],
  ['macro name shared with the PC script', "var MACRO_NAME = 'CREW_TAM';", "var MACRO_NAME = 'BLADES_TAM';"],
  ['state key shared with the PC script', "var STATE_KEY = 'BitDCrewTAM';", "var STATE_KEY = 'BitDTAM';"],
  ['entanglement table cell wrong', "['Reprisals', 'Unquiet Dead']", "['Reprisals', 'Rivals']"],
  ['entanglement Heat 6 column starts at 7', "w.heat >= 6 ? 2 : (w.heat >= 4 ? 1 : 0)", "w.heat >= 7 ? 2 : (w.heat >= 4 ? 1 : 0)"],
  ['entanglement zero dice take the highest', "name: clean(t.c.name), heat: heat, dice: pool > 0 ? pool : 2, lowest: pool <= 0 }", "name: clean(t.c.name), heat: heat, dice: pool > 0 ? pool : 2, lowest: false }"],
  ['Downtime coin written to the standard track', "return mods(cid).downtime ? { attr: 'crewcoin_dc', max: 24 }", "return mods(cid).downtime ? { attr: 'crewcoin', max: 24 }"],
  ['vault holds 6', "4 + (v1 ? 8 : 0) + (v2 ? 12 : 0)", "4 + (v1 ? 6 : 0) + (v2 ? 12 : 0)"],
  ['hold strong only above Tier', "getNum(cid, 'turf', 0) >= getNum(cid, 'crew_tier', 0) ? 'strong' : 'weak'", "getNum(cid, 'turf', 0) > getNum(cid, 'crew_tier', 0) ? 'strong' : 'weak'"],
  ['5th Wanted box reads the wrong attribute', "{ attr: 'wantedDC', max: 5, label", "{ attr: 'wanted', max: 5, label"],
  ['a callback on the Tier roll', "'{{title=^{crew_tier}}} {{subtitle=^{roll_their}}} {{' + diceField(pool) + '}}' + tail(cid, t.c);\n      sendChat('player|' + msg.playerid, text);", "'{{title=^{crew_tier}}} {{subtitle=^{roll_their}}} {{' + diceField(pool) + '}}' + tail(cid, t.c);\n      sendChat('player|' + msg.playerid, text, function () {});"],
  ['bar 1 max of 12', "bar1_max: HEAT_MAX", "bar1_max: 12"],
  ['bar 1 not linked to heat', "tok.set({ bar1_link: a.id });", "tok.set({ bar2_link: a.id });"],
  ['Slippery does nothing', "Math.max(0, actual - 1)", "actual"],
  ['core advancement reminder with Downtime on', "before + 1 >= CREW_XP_MAX && !m.downtime", "before + 1 >= CREW_XP_MAX"],
  ['No Traces takes 2', "total -= 1; parts.push('No Traces -1');", "total -= 2; parts.push('No Traces -1');"],
  ['payoff steps can repeat', "flow.done[step] = true;\n    return flow;", "return flow;"],
  ['Incarceration keeps Heat', "setAttr(cid, 'heat', 0);\n        syncHeatBars(cid);", "syncHeatBars(cid);"],
  ['fencing Heat 1 per 2 Coin', "Math.floor(coins[code] / 4)", "Math.floor(coins[code] / 2)"],
  ['bonus dice not limited', "bonus = clamp(bonus, -3, 6);", ""],
  ['cohort ignores elite or expert', "((cohortType(cid, prefix) === 'elite' || cohortType(cid, prefix) === 'expert') ? 1 : 0)", "0"],
  ['impaired adds a die', "- getNum(cid, prefix + '_impaired', 0) +", "+ getNum(cid, prefix + '_impaired', 0) +"],
  ['Wanted level gained on Heat 8', "var res = applyHeat(cid, cur, 0);", "var res = applyHeat(cid, cur + 1, 0);"],
  ['Downtime crew can roll Entanglement', "if (m.downtime) {\n        whisper(msg, 'BitDCrew: Deep Cuts Downtime has no entanglement roll.", "if (false) {\n        whisper(msg, 'BitDCrew: Deep Cuts Downtime has no entanglement roll."],
  ['deposit ignores vault room', "Math.max(0, Math.min(coinCapacity(cid), tr.max) - cur)", "Math.max(0, tr.max - cur)"],
  ['half deposit rounds up', "(code === 'half' ? Math.floor(flow.net / 2) : 0)", "(code === 'half' ? Math.ceil(flow.net / 2) : 0)"],
  ['abilities menu lists unticked', "if (String(getAttrByName(cid, 'repeating_crewability_' + r.row + '_check')) !== '1') { return; }", ""],
  ['clock may pass its size', "var next = clamp(k.progress + (delta > 0 ? 1 : -1), 0, k.size);", "var next = clamp(k.progress + (delta > 0 ? 1 : -1), 0, 99);"],
  ["Reduce Heat takes 2", "    var res = addHeat(cid, -1);\n    note(msg, t.c, 'Heat', 'Heat ' + res.after", "    var res = addHeat(cid, -2);\n    note(msg, t.c, 'Heat', 'Heat ' + res.after"],
  ["Rep not capped at 12", "Math.min(REP_MAX, before + want)", "before + want"],
  ["Leverage on a gain of 0", "(!noLeverage && n > 0 && crewAbilityOn(cid, 'Leverage')) ? 1 : 0", "(!noLeverage && crewAbilityOn(cid, 'Leverage')) ? 1 : 0"],
  ["Leverage gives +2", "(!noLeverage && n > 0 && crewAbilityOn(cid, 'Leverage')) ? 1 : 0", "(!noLeverage && n > 0 && crewAbilityOn(cid, 'Leverage')) ? 2 : 0"],
  ["Misdirection gives up the larger half", "give = Math.floor(earned / 2);", "give = Math.ceil(earned / 2);"],
  ["Misdirection halves the Rep that fit, not the Rep earned", "give = Math.floor(earned / 2);", "give = Math.floor(rg.applied / 2);"],
  ["Misdirection halves the Rep asked, not earned (no Leverage)", "var earned = repGain + rg.bonus,", "var earned = repGain,"],
  ["Misdirection offered at an earn of 1", "      if (give >= 1) {\n        L.push('Misdirection: you may give up", "      if (give >= 0) {\n        L.push('Misdirection: you may give up"],
  ["Misdirection offered without the ability", "    if (crewAbilityOn(cid, 'Misdirection')) {\n      if (give >= 1) {", "    if (crewAbilityOn(cid, 'Misdirection') || crewAbilityListed(cid, 'Misdirection')) {\n      if (give >= 1) {"],
  ["Misdirection withheld in silence (no reason)", "        L.push('Misdirection is not offered: half of the Rep earned (' + earned + '), rounded down, is 0.');\n", ""],
  ["unticked Misdirection says nothing", "    } else if (crewAbilityListed(cid, 'Misdirection')) {", "    } else if (false) {"],
  ["crews without Misdirection are told about it", "    } else if (crewAbilityListed(cid, 'Misdirection')) {", "    } else if (true) {"],
  ["Score recorded never mentions Rep that did not fit", "flow.repFit !== undefined && flow.repFit < flow.repGain ?", "false ?"],
  ["Score recorded always mentions fit", "flow.repFit !== undefined && flow.repFit < flow.repGain ?", "flow.repFit !== undefined ?"],
  ["core Score card forgets to name the rule set", "'Downtime module off: this is the core Score, Heat only. Rep and the Payoff are not tracked.'", "'Core Score.'"],
  ["No Traces Rep at End Downtime with Heat 1", "      if (heat === 0) {\n        r = gainRep(cid, 1);", "      if (heat <= 1) {\n        r = gainRep(cid, 1);"],
  ["No Traces gives 2 Rep at End Downtime", "r = gainRep(cid, 1);", "r = gainRep(cid, 2);"],
  ["End Downtime leaves the Downtime open", "    d.ended = true;\n    L.push(d.startHeat", "    d.ended = false;\n    L.push(d.startHeat"],
  ["Just Passing Through takes 2 Heat", "res = addHeat(cid, -1);\n        d.log.push('Just Passing Through", "res = addHeat(cid, -2);\n        d.log.push('Just Passing Through"],
  ["Just Passing Through not once per Downtime", "        d.used.jpt = true;\n", ""],
  ["Just Passing Through spent at Heat 0", "if (getNum(cid, 'heat', 0) < 1) { note(msg, t.c, 'Heat', 'Heat 0', 'There is no Heat to reduce, so", "if (false) { note(msg, t.c, 'Heat', 'Heat 0', 'There is no Heat to reduce, so"],
  ["Just Passing Through button at Heat 0", "ab['just passing through'] === true && !d.used.jpt && heat > 0", "ab['just passing through'] === true && !d.used.jpt"],
  ["Reduce Heat buttons at Heat 0", "    if (heat > 0) {\n      L.push('Reduce Heat by 1", "    if (true) {\n      L.push('Reduce Heat by 1"],
  ["Downtime id not checked", "if (!d || !o.idx || d.id !== o.idx) {", "if (!d) {"],
  ["Heat and Hold on a crew without Downtime", "    if (!mods(cid).downtime) { whisper(msg, 'BitDCrew: Heat and Hold is a Deep Cuts Downtime step, and the module is off for this crew.'); return; }\n    var d = openDowntime(cid);", "    var d = openDowntime(cid);"],
  ["Score does not start a Downtime", "    startDowntime(cid, 'score');\n", ""],
  ["no Heat and Hold card after the deposit", "    var dd = openDowntime(cid);\n    if (dd) {", "    var dd = null;\n    if (dd) {"],
  ["an ended Downtime still counts as open", "return (d && !d.ended) ? d : null;", "return d || null;"],
  ["a new Downtime keeps the old used list", "used: {}, pending: {}, log: [], ended: false", "used: (prev ? prev.used : {}), pending: {}, log: [], ended: false"],
  ["party tag wrong", "var PARTY_TAG = '_roll20_internal_party_tag_';", "var PARTY_TAG = '_roll20_party_';"],
  ["party flag read from arrays only", "(typeof t === 'string' ? t : JSON.stringify(t)).indexOf(PARTY_TAG) >= 0;", "(typeof t === 'string' ? '' : JSON.stringify(t)).indexOf(PARTY_TAG) >= 0;"],
  ["party count includes crews", "return partyCharacters().filter(function (c) { return getAttr(c.id, 'sheet_type', 'character') === 'character'; }).length;", "return partyCharacters().length;"],
  ["empty party still scores", "if (pn < 1) {", "if (pn < 0) {"],
  ["party probe open to players", "    if (!playerIsGM(msg.playerid)) { whisper(msg, 'BitDCrew: only the GM can run the party check.'); return; }\n", ""],
  ["debug always on", "function dbg(text) { if (botState().debug) {", "function dbg(text) { if (true) {"],
  ["debug switch open to players", "    if (!playerIsGM(msg.playerid)) { whisper(msg, 'BitDCrew: only the GM can change debug logging.'); return; }\n", ""],
  ["Payoff prompt without the party option", "' ?{PCs for the Payoff (1 Coin each)|All party members,party|'", "' ?{PCs for the Payoff (1 Coin each)|'"],
  ["Downtime state not created", "    state[STATE_KEY].downtime = state[STATE_KEY].downtime || {};\n", ""],
  ["Status says Just Passing Through is active at Heat 5", "(heat <= 4 ? 'active now'", "(heat <= 5 ? 'active now'"],
  ["Engagement without the die for luck", "var pool = 1, parts = ['1 luck'];", "var pool = 0, parts = ['1 luck'];"],
  ["Engagement bonus counts double", "pool += 1; parts.push('+1 ' + name)", "pool += 2; parts.push('+1 ' + name)"],
  ["Door Kickers on stealth too", "name: 'Door Kickers', plans: ['assault'] }", "name: 'Door Kickers', plans: ['assault', 'stealth'] }"],
  ["Second Story on assault too", "name: 'Second Story', plans: ['stealth'] }", "name: 'Second Story', plans: ['stealth', 'assault'] }"],
  ["Predators on stealth only", "plans: ['stealth', 'deception'], ask: 'the goal is murder' }", "plans: ['stealth'], ask: 'the goal is murder' }"],
  ["Predators is automatic, not asked", "plans: ['stealth', 'deception'], ask: 'the goal is murder' }", "plans: ['stealth', 'deception'] }"],
  ["Deadly Focus (River) is automated", "{ kind: 'ability', name: 'Second Story', plans: ['stealth'] },", "{ kind: 'ability', name: 'Second Story', plans: ['stealth'] },\n    { kind: 'ability', name: 'Deadly Focus', plans: PLAN_TYPES },"],
  ["Cover Identities follows the sheet (transport)", "name: 'Cover Identities', plans: ['deception', 'social'], byType", "name: 'Cover Identities', plans: ['deception', 'transport'], byType"],
  ["The Governor (River) is automated", "{ kind: 'claim', name: 'Secret Routes', plans: ['transport'] }\n  ];", "{ kind: 'claim', name: 'Secret Routes', plans: ['transport'] },\n    { kind: 'claim', name: 'The Governor', plans: PLAN_TYPES }\n  ];"],
  ["unticked claims count", "if (!isOn(cid, 'claim_' + i + '_check')) { continue; }\n      var nm = normName(getAttrByName(cid, 'claim_' + i + '_name')).replace(/_/g, ' ').replace(/^claim /, '');\n      if (nm) { on[nm] = true; }", "if (false) { continue; }\n      var nm = normName(getAttrByName(cid, 'claim_' + i + '_name')).replace(/_/g, ' ').replace(/^claim /, '');\n      if (nm) { on[nm] = true; }"],
  ["unticked income claims count", "if (!isOn(cid, 'claim_' + i + '_check')) { continue; }\n      var nm = normName(getAttrByName(cid, 'claim_' + i + '_name')).replace(/_/g, ' ').replace(/^claim /, '');\n      CLAIM_INCOME", "if (false) { continue; }\n      var nm = normName(getAttrByName(cid, 'claim_' + i + '_name')).replace(/_/g, ' ').replace(/^claim /, '');\n      CLAIM_INCOME"],
  ["claim key prefix not removed", ".replace(/_/g, ' ').replace(/^claim /, '');\n      if (nm) { on[nm] = true; }", ".replace(/_/g, ' ');\n      if (nm) { on[nm] = true; }"],
  ["income claim key prefix not removed", ".replace(/_/g, ' ').replace(/^claim /, '');\n      CLAIM_INCOME", ".replace(/_/g, ' ');\n      CLAIM_INCOME"],
  ["transport is not a plan type", "'occult', 'social', 'transport'];\n  var ENG_SOURCES", "'occult', 'social'];\n  var ENG_SOURCES"],
  ["other elements range 9", "var ENG_OTHER_MAX = 3;", "var ENG_OTHER_MAX = 9;"],
  ["zero pool says nothing", "' = ' + Math.max(flow.pool, 0) + 'd' +\n      (flow.pool <= 0 ? ' (no dice: roll 2d and keep the lowest)' : '') + '.';", "' = ' + Math.max(flow.pool, 0) + 'd' + '.';"],
  ["stale Engagement macro accepted", "if (o.pos.length !== 5) {", "if (false) {"],
  ["Engagement card is not an engagement card", "{{subtitle=^{roll_for}}} {{title-engagement=1}} {{title=^{engagement}}} {{'", "{{subtitle=^{roll_for}}} {{title-fortune=1}} {{title=^{engagement}}} {{'"],
  ["approach default is not Neither", "|Neither,0|Bold or daring (+1d),1|", "|Bold or daring (+1d),1|Neither,0|"],
  ["Zealotry reminder missing", "['Zealotry', 'Zealotry: your cohorts", "['Zealotri', 'Zealotry: your cohorts"],
  ["reminders shown for unticked abilities", "if (on[normName(r[0])] === true) { L.push(r[1]); }", "if (true) { L.push(r[1]); }"],
  ["Edge limit 999", "EDGE_MAX = 99;", "EDGE_MAX = 999;"],
  
  ["Begin score ignores the Action module", "if (!mods(cid).action) { whisper(msg, 'BitDCrew: Edge comes from", "if (false) { whisper(msg, 'BitDCrew: Edge comes from"],
  ["Begin score ignores the ability", "if (!crewAbilityOn(cid, 'Bound in Darkness')) {", "if (false) {"],
  
  ["party PCs include crew sheets", "=== 'character'; });\n  }\n  function edgeOf", "=== 'character' || true; });\n  }\n  function edgeOf"],
  ["Edge goes to every character", "    var pcs = partyPcs();\n    if (code === 'all') {", "    var pcs = findObjs({ _type: 'character' });\n    if (code === 'all') {"],
  ["All gives 2 Edge", "var before = edgeOf(pc.id), after = setEdgeOf(pc.id, before + 1);\n        L.push(btn(pc.get('name')) + ' Edge ' + before", "var before = edgeOf(pc.id), after = setEdgeOf(pc.id, before + 2);\n        L.push(btn(pc.get('name')) + ' Edge ' + before"],
  ["All ignores who already got Edge", "if (flow.done[step]) { return; }", "if (false) { return; }"],
  ["a PC button works more than once", "if (flow.done[step1]) {", "if (false) {"],
  ["Edge token bar not set", "    setAttr(pcId, EDGE_ATTR, n);\n    syncEdgeBars(pcId);\n", "    setAttr(pcId, EDGE_ATTR, n);\n"],
  ["Clear Edge clears nothing", "if (had > 0) { setEdgeOf(pc.id, 0);", "if (had > 0) {"],
  ["Clear Edge offered when nobody has Edge", "        if (holders.length) {", "        if (true) {"],
  ["Clear Edge works more than once", "flowFor(msg, t, o, 'edgeclear')", "flowFor(msg, t, o, 'edgeclear' + Date.now() + Math.random())"],
  ["Edge line on a crew without the Action module", "    if (mods(cid).action) {\n      var pcs0", "    if (true) {\n      var pcs0"],
  ["Begin score card accepts any flow", "flow.cid !== cid || flow.kind !== 'edge')", "flow.cid !== cid)"],
  ["Heat claim takes 3", "var HEAT_CLAIM = 2;", "var HEAT_CLAIM = 3;"],
  ["Heat claim can push Heat below 0", "if (total < 0) { total = 0; parts.push('not below 0'); }", "if (total < 0) { parts.push('not below 0'); }"],
  ["Heat claim applied to a total of 0", "    if (total < 1) { return total; }\n    var cl = claimsOn(cid);", "    if (total < 0) { return total; }\n    var cl = claimsOn(cid);"],
  ["core Score ignores Heat claims", "    total = applyHeatClaims(cid, total, parts);\n    var res = addHeat(cid, total);\n    var L = ['Heat +' + total", "    var res = addHeat(cid, total);\n    var L = ['Heat +' + total"],
  ["Deep Cuts Score ignores Heat claims", "    total = applyHeatClaims(cid, total, parts);\n    var res = addHeat(cid, total);\n    L.push(", "    var res = addHeat(cid, total);\n    L.push("],
  ["Rep from the Heat before the claim", "Math.floor(total / 2) + Math.max(0, tTier - tier) + (vt ? 1 : 0)", "Math.floor((total + 2) / 2) + Math.max(0, tTier - tier) + (vt ? 1 : 0)"],
  ["Victim Trophies gives 2", "+ (vt ? 1 : 0), rg = gainRep(cid, repGain)", "+ (vt ? 2 : 0), rg = gainRep(cid, repGain)"],
  ["Victim Trophies ignored", "var vt = claimHas(claimsOn(cid), [CLAIM_REP_AUTO]);", "var vt = false;"],
  ["claim Rep boosted by Leverage", "var rg = gainRep(cid, def.rep, true);", "var rg = gainRep(cid, def.rep);"],
  ["Publicity gives 3", "{ name: 'Publicity', label: 'takedown score', rep: 2 }", "{ name: 'Publicity', label: 'takedown score', rep: 3 }"],
  ["claim button works more than once", "var flow = flowFor(msg, t, o, code); if (!flow) { return; }\n    if (m[1] === 'rep') {", "var flow = flowFor(msg, t, o, code + Math.random()); if (!flow) { return; }\n    if (m[1] === 'rep') {"],
  ["Coin claim gives 3", "flow.base += 2;", "flow.base += 3;"],
  ["Coin claim after the seized step", "if (pre && pre.cid === cid && m[1] === 'coin' && pre.done.seized) {", "if (false) {"],
  ["unticked claim button accepted", "if (!claimHas(claimsOn(cid), names)) { whisper(msg, 'BitDCrew: ' + label", "if (false) { whisper(msg, 'BitDCrew: ' + label"],
  ["Rep claim buttons for claims not ticked", "if (claimHas(cl2, [c.name])) { claimBtns.push", "if (true) { claimBtns.push"],
  ["Surplus Cache spelling missing", "names: ['Surplus Caches', 'Surplus Cache']", "names: ['Surplus Caches']"],
  ["Covert Drop spelling missing", "names: ['Covert Drops', 'Covert Drop']", "names: ['Covert Drops']"],
  ["Terrorized Citizens button label wrong", "{ names: ['Terrorized Citizens'], label: 'battle or extortion' }", "{ names: ['Terrorized Citizens'], label: 'battle' }"],
  ["Offertory button missing", "    { names: ['Offertory'], label: 'occult operations' },\n", ""],
  ["Street Fence tied to the wrong claim", "{ names: ['Street Fence'], label: 'lower-class targets' }", "{ names: ['Street Fences'], label: 'lower-class targets' }"],
  ["Luxury Fence label wrong", "{ names: ['Luxury Fence'], label: 'high-class targets' }", "{ names: ['Luxury Fence'], label: 'lower-class targets' }"],
  ["Covert Drops dropped from the Coin claims", "    { names: ['Covert Drops', 'Covert Drop'], label: 'espionage or sabotage' }\n  ];", "  ];"],
  ["income rolls Tier plus 1", "diceField(tier) + '}} {{notes='", "diceField(tier + 1) + '}} {{notes='"],
  ["income is the die, not die minus Heat", "var coin = Math.max(0, die - w.heat);", "var coin = die;"],
  ["income can go negative", "var coin = Math.max(0, die - w.heat);", "var coin = die - w.heat;"],
  ["income reads Heat after the roll", "var coin = Math.max(0, die - w.heat);", "var coin = Math.max(0, die - getNum(w.cid, 'heat', 0));"],
  ["income claim rolls more than once", "if (d.used['inc' + slot]) { note(", "if (false) { note("],
  ["income is added more than once", "if (d.used['incpay' + ps]) {", "if (false) {"],
  ["income ignores vault room", "put = Math.min(pend, iroom);", "put = pend;"],
  ["income button adds nothing", "if (put > 0) { setAttr(cid, itr.attr, icur + put); }", "if (put > 0) { }"],
  ["Info Biz counted as income", "'Protection Racket', 'Side Business'];", "'Protection Racket', 'Side Business', 'Info Biz'];"],
  ["income claims missing from Heat and Hold", "    var inc = incomeClaims(cid);\n    if (inc.length) {", "    var inc = incomeClaims(cid);\n    if (false) {"],
  ["a roll that never comes back is silent", "      watching.splice(i, 1);\n      whisper(msg, failText);", "      watching.splice(i, 1);"],
  ["Status hides the claims", "if (cip.length) { L.push('Claims the script counts: '", "if (false) { L.push('Claims the script counts: '"],
  ["core crews list Deep Cuts claims", "    if (dt) {\n      if (claimHas(cl, [CLAIM_REP_AUTO]))", "    if (true) {\n      if (claimHas(cl, [CLAIM_REP_AUTO]))"],
  ["Engagement arithmetic card missing", "    sendChat('player|' + msg.playerid, broadcast(t.c, { type: 'Engagement', title: Math.max(pool, 0) + 'd', content: clean(engagementLine(flow)) }));\n", ""],
  ["Engagement arithmetic put back on the unreadable notes line", "{{' + diceField(pool) + '}}' +\n      tail(cid, t.c));", "{{' + diceField(pool) + '}} {{notes=' + clean(engagementLine(flow)) + '}}' +\n      tail(cid, t.c));"],
  ["approach counted backwards", "if (ans[k]) { pool += ans[k]; parts.push(", "if (ans[k]) { pool -= ans[k]; parts.push("],
  ["other elements counted double", "if (ans[3]) { pool += ans[3]; parts.push(", "if (ans[3]) { pool += 2 * ans[3]; parts.push("],
  ["questions allow +2", "if (isNaN(ans[i]) || ans[i] < -1 || ans[i] > 1) { bad = true; }", "if (isNaN(ans[i]) || ans[i] < -2 || ans[i] > 2) { bad = true; }"],
  ["unknown plan type accepted", "bad = PLAN_TYPES.indexOf(plan) < 0;", "bad = false;"],
  ["Predators asked on every plan", "if (!src.ask || ab[normName(src.name)] !== true || src.plans.indexOf(plan) < 0) { return; }", "if (!src.ask || ab[normName(src.name)] !== true) { return; }"],
  ["Predators asked when not ticked", "if (!src.ask || ab[normName(src.name)] !== true || src.plans.indexOf(plan) < 0) { return; }", "if (!src.ask || src.plans.indexOf(plan) < 0) { return; }"],
  ["every character counts as a Party PC for engagement", "    partyPcs().forEach(function (pc) {\n      var have = tickedRows(pc.id, 'ability')", "    findObjs({ _type: 'character' }).forEach(function (pc) {\n      var have = tickedRows(pc.id, 'ability')"],
  ["unticked abilities count", "if (String(getAttrByName(cid, 'repeating_' + section + '_' + r.row + '_check')) === '1') {", "if (true) {"],
  ["an extra gives 2d", "flow.done[x.id] = true; flow.pool += 1;", "flow.done[x.id] = true; flow.pool += 2;"],
  ["an extra can be added twice", "if (flow.done[x.id]) { note(", "if (false) { note("],
  ["a rolled engagement can be rolled again", "if (flow.rolled) { note(msg, t.c, 'Engagement', 'Already rolled'", "if (false) { note(msg, t.c, 'Engagement', 'Already rolled'"],
  ["Roll does not mark the card rolled", "    flow.rolled = true;\n    finishEngagement(msg, t, flow);", "    finishEngagement(msg, t, flow);"],
  ["any flow works as an engagement card", "flow.cid !== t.ch.id || flow.kind !== 'eng')", "flow.cid !== t.ch.id)"],
  ["the confirm card is whispered", "    sendChat('player|' + msg.playerid, broadcast(t.c, { type: 'Engagement', title: 'Confirm'", "    whisper(msg, broadcast(t.c, { type: 'Engagement', title: 'Confirm'"],
  ["automatic sources are not counted before the card", "    engagementBonuses(cid, plan).forEach(function (name) { pool += 1; parts.push('+1 ' + name); });\n", ""],
  ["Weaving the Web not recognised", "{ name: 'Weaving the Web', ask: 'gathered info' }", "{ name: 'Weaving the Webb', ask: 'gathered info' }"],
  ["Eye for Weakness not recognised", "{ name: 'Eye for Weakness', ask: 'used it to plan' }", "{ name: 'Eye for Weaknesss', ask: 'used it to plan' }"],
  ["long PC names push the +1d off the button", "label: who.slice(0, 16) + ', '", "label: who + ', '"],
  ["no position named after an engagement roll", "var AUTO_ENGAGEMENT = true;", "var AUTO_ENGAGEMENT = false;"],
  ["engagement dice count wrong at zero", "dice: pool > 0 ? pool : 2, lowest: pool <= 0 }, msg,", "dice: pool, lowest: pool <= 0 }, msg,"],
  ["zero dice not read as the lowest", "dice: pool > 0 ? pool : 2, lowest: pool <= 0 }, msg,", "dice: pool > 0 ? pool : 2, lowest: false }, msg,"],
  ["4 is desperate", "else if (die >= 4) { title = 'Risky position'", "else if (die >= 5) { title = 'Risky position'"],
  ["5 is controlled", "else if (die >= 6) { title = 'Controlled position'", "else if (die >= 5) { title = 'Controlled position'"],
  ["one 6 is a critical", "var crit = !w.lowest && sixes >= 2, title, text;", "var crit = !w.lowest && sixes >= 1, title, text;"],
  ["zero dice can be a critical", "var crit = !w.lowest && sixes >= 2, title, text;", "var crit = sixes >= 2, title, text;"],
  ["the position is whispered", "    sendChat('player|' + w.pid, broadcast(info(w.cid), { type: 'Engagement', title: title,", "    whisper(msg, broadcast(info(w.cid), { type: 'Engagement', title: title,"],
  ["other elements cannot be negative in the macro", "|0|1|2|3|-1|-2|-3}", "|0|1|2|3}"],
  ["Begin score offered without the Action module", "if (mods(cid).action && crewAbilityOn(cid, 'Bound in Darkness')) {\n      var edgeCard", "if (crewAbilityOn(cid, 'Bound in Darkness')) {\n      var edgeCard"],
  ["Begin score offered without Bound in Darkness", "if (mods(cid).action && crewAbilityOn(cid, 'Bound in Darkness')) {\n      var edgeCard", "if (mods(cid).action) {\n      var edgeCard"],
  ["Begin score with an empty party", "    if (!card) {\n      whisper(msg, 'BitDCrew: no player characters are marked as Party members, so there is nobody", "    if (false) {\n      whisper(msg, 'BitDCrew: no player characters are marked as Party members, so there is nobody"],
  ["Begin score card is whispered, not shown to the table", "if (edgeCard) { sendChat('player|' + msg.playerid, edgeCard); }", "if (edgeCard) { whisper(msg, edgeCard); }"],
  ["empty party is silent after the engagement roll", "      else { whisper(msg, 'BitDCrew: Bound in Darkness is ticked, but", "      else if (false) { whisper(msg, 'BitDCrew: Bound in Darkness is ticked, but"],
  ["Downtime button on a core crew", "if (dt) { list.push([ABILITY_NAMES[4], CMD + ' hh']); }", "if (true) { list.push([ABILITY_NAMES[4], CMD + ' hh']); }"],
  ["Downtime button runs the wrong command", "list.push([ABILITY_NAMES[4], CMD + ' hh']);", "list.push([ABILITY_NAMES[4], CMD + ' status']);"],
  ["Adjust still carries Heat and Hold", "(dt ? '|Debt clock +1,debt+1|Debt clock -1,debt-1' : '');", "(dt ? '|Debt clock +1,debt+1|Debt clock -1,debt-1|Downtime: Heat and Hold,hh' : '');"],
  ["Debt clock on a core crew", "(dt ? '|Debt clock +1,debt+1|Debt clock -1,debt-1' : '');", "(true ? '|Debt clock +1,debt+1|Debt clock -1,debt-1' : '');"],
  ["Adjust loses a counter", "'|Mark crew XP,xp+1' +", "'' +"],
  ["favorites carry no triangle on the button", "btn((c.fav ? TRIANGLE + ' ' : '') + c.name)", "btn(c.name)"],
  ["every contact button carries the triangle", "btn((c.fav ? TRIANGLE + ' ' : '') + c.name)", "btn(TRIANGLE + ' ' + c.name)"],
  ["favorites carry no triangle in the output title", "title: (c.fav ? TRIANGLE + ' ' : '') + c.name,", "title: c.name,"],
  ["the output header never says favorite", "type: c.fav ? 'Favorite contact' : 'Contact',", "type: 'Contact',"],
  ["any value but 0 counts as a favorite", "'_check')) === '1' });", "'_check')) !== '0' });"],
  ["rows with no name are listed", "      if (!name) { return; }\n      out.push({ row: r.row", "      if (false) { return; }\n      out.push({ row: r.row"],
  ["notes keep their brackets", ".replace(/\\[/g, '(').replace(/\\]/g, ')')", ""],
  ["notes keep macro openers", ".replace(/([@%?&])\\{/g, '$1 {')", ""],
  ["notes are not cut", "if (t.length > max) { t = t.slice(0, max)", "if (false) { t = t.slice(0, max)"],
  ["notes cap is 5000", "var NOTES_MAX = 2000;", "var NOTES_MAX = 5000;"],
  ["blank lines are not tidied", ".replace(/\\n{3,}/g, NL + NL)", ""],
  ["a name can break the title across lines", "var name = chatNotes(r.value, 100000).replace(/\\s*\\n\\s*/g, ' ').slice(0, 120)", "var name = chatNotes(r.value, 100000).slice(0, 120)"],
  ["the contact notes are whispered, not shown to the table", "    sendChat('player|' + msg.playerid, broadcast(t.c, {\n      type: c.fav ? 'Favorite contact'", "    whisper(msg, broadcast(t.c, {\n      type: c.fav ? 'Favorite contact'"],
  ["the contacts menu is public", "    whisper(msg, broadcast(t.c, {\n      type: 'Contacts',", "    sendChat('player|' + msg.playerid, broadcast(t.c, {\n      type: 'Contacts',"],
  ["contacts are not in sheet order", "    });\n    return out;\n  }\n\n  function doContacts", "    });\n    return out.reverse();\n  }\n\n  function doContacts"],
  ["a deleted contact is still shown", "if (!c) { whisper(msg, 'BitDCrew: that contact is no longer on the sheet.", "if (false) { whisper(msg, 'BitDCrew: that contact is no longer on the sheet."],
  ["no Contacts button", "      [ABILITY_NAMES[6], CMD + ' contacts'],\n", ""],
  ["the Contacts button is named so it sorts wrongly", "'6. Abilities', '6a. Contacts',", "'6. Abilities', '10. Contacts',"],
  ["the Contacts button runs the wrong command", "[ABILITY_NAMES[6], CMD + ' contacts'],", "[ABILITY_NAMES[6], CMD + ' abilities'],"],
  ["the menu does not explain the triangle", "NL + TRIANGLE + ' marks a favorite contact.'", "NL + ''"],
  ["claim buttons carry no held marker", "lines.push('[' + btn((s.held ? G_ON : G_OFF) + ' ' + s.name) + ']", "lines.push('[' + btn(s.name) + ']"],
  ["every claim button says held", "lines.push('[' + btn((s.held ? G_ON : G_OFF) + ' ' + s.name) + ']", "lines.push('[' + btn(G_ON + ' ' + s.name) + ']"],
  ["the Turf button counts slots, not held claims", "var h = turfs.filter(function (x) { return x.held; }).length;\n        lines.push", "var h = turfs.length;\n        lines.push"],
  ["every turf slot gets its own button", "        if (turfDone) { return; }\n", ""],
  ["the claim card header never says not held", "held ? 'Claim held' : 'Claim not held', (held ? G_ON", "'Claim held', (held ? G_ON"],
  ["the claim card title has no marker", "(held ? G_ON : G_OFF) + ' ' + title, lines);", "title, lines);"],
  ["the card always says held", "L.push(bold(s.held ? 'Held by this crew.' : 'Not held by this crew.'));", "L.push(bold('Held by this crew.'));"],
  ["claim wording ignores the crew type", "if (entries[i][0].indexOf(type) >= 0) { return entries[i][1]; }", "if (true) { return entries[i][1]; }"],
  ["the crew type text is not read", "if (tv.indexOf(CREW_STEMS[i][0]) >= 0) { return CREW_STEMS[i][1]; }", "if (false) { return CREW_STEMS[i][1]; }"],
  ["an unknown crew type is not inferred", "if (counts[c] > bestN) { best = c; bestN = counts[c]; }", "if (false) { best = c; bestN = counts[c]; }"],
  ["the Deep Cuts claim text ignores the module", "if (isOn(cid, dc.attr)) {", "if (true) {"],
  ["Warehouses follows the wrong module", "'warehouses': { attr: 'setting_dc_downtime',", "'warehouses': { attr: 'setting_dc_action',"],
  ["the sheet text line is dropped", "    if (s.sheet) { L.push(ruleLine('On the sheet:', s.sheet, true)); }\n", ""],
  ["sheet claim text is posted raw", "chatNotes(getAttrByName(cid, 'claim_' + i + '_desc'), 400)", "String(getAttrByName(cid, 'claim_' + i + '_desc'))"],
  ["claim names from the sheet are always title-cased", "    if (!key) { return n; }\n", ""],
  ["small words are capitalised", "var SMALL_WORDS = ' the of and a an in on ';", "var SMALL_WORDS = ' ';"],
  ["a turf slot can be asked for by number", "return x.slot === n && x.key !== 'turf'; })[0];", "return x.slot === n; })[0];"],
  ["the claims menu does not explain the markers", "NL + ital(G_ON + ' held by the crew, ' + G_OFF + ' not held.')", "NL + ''"],
  ["the claim card is whispered, not shown to the table", "    sendChat('player|' + msg.playerid, broadcast(t.c, { type: type, title: title, content:", "    whisper(msg, broadcast(t.c, { type: type, title: title, content:"],
  ["the claims menu is public", "    whisper(msg, broadcast(t.c, {\n      type: 'Claims',", "    sendChat('player|' + msg.playerid, broadcast(t.c, {\n      type: 'Claims',"],
  ["the Turf card puts the wrong rule in force", "var tmain = dtOn ? ruleLine(", "var tmain = !dtOn ? ruleLine("],
  ["no Claims button", "      [ABILITY_NAMES[7], CMD + ' claims'],\n", ""],
  ["the Claims button sorts wrongly", "'6a. Contacts', '6b. Claims',", "'6a. Contacts', '10. Claims',"],
  ["the Crew Upgrades button sorts wrongly", "'6c. Crew Upgrades', '7. Adjust'", "'10. Crew Upgrades', '7. Adjust'"],
  ["Hawkers Cover Identities stays social", "byType: { hawkers: ['deception', 'transport'] }", "byType: { hawkers: ['deception', 'social'] }"],
  ["Assassins Cover Identities gets transport too", "byType: { hawkers: ['deception', 'transport'] }", "byType: { assassins: ['deception', 'transport'], hawkers: ['deception', 'transport'] }"],
  ["the crew type is ignored for engagement plans", "return (src.byType && src.byType[type]) || src.plans;", "return src.plans;"],
  ["Status lists the default plans", "engPlans(src, type).join(' or ')", "src.plans.join(' or ')"],
  ["Hagfish Farm has no Deep Cuts text", "    'hagfish farm': { attr: 'setting_dc_downtime', module: 'Downtime', text: 'Body disposal + counts as turf. (Deep Cuts crew sheets v1.2b)' },\n", ""],
  ["Hagfish Farm follows the Action module", "'hagfish farm': { attr: 'setting_dc_downtime'", "'hagfish farm': { attr: 'setting_dc_action'"],
  ["Hagfish Farm text drops counts as turf", "text: 'Body disposal + counts as turf. (Deep Cuts", "text: 'Body disposal. (Deep Cuts"],
  ["the turf check ignores Hagfish Farm", "(dt && nm === 'hagfish farm')", "false"],
  ["the turf check counts Hagfish Farm with Downtime off", "(dt && nm === 'hagfish farm')", "(nm === 'hagfish farm')"],
  ["the Turf card omits Hagfish Farm", "if (dtOn && hag) {", "if (false) {"],
  ["the Status turf note forgets Hagfish Farm", "(dt && claimsOn(cid)['hagfish farm'] === true ? ' (counting Hagfish Farm)' : '')", "''"],
  ["the Cover Identities ruling applies to every crew", "ruling = (CLAIM_TYPE_RULING[s.key] || {})[type]", "ruling = (CLAIM_TYPE_RULING[s.key] || {}).hawkers"],
  ["the ruling card does not mark the core text unused", "alt: book ? ruleLine('Core book text (not used for this crew):', book, true) : '' };", "alt: '' };"],
  ["Infirmary has no Deep Cuts text", "    'infirmary': { attr: 'setting_dc_downtime', module: 'Downtime', text: HEALING_TICK_DC },\n", ""],
  ["Sacred Nexus has no Deep Cuts text", "    'sacred nexus': { attr: 'setting_dc_downtime', module: 'Downtime', text: HEALING_TICK_DC },\n", ""],
  ["Infirmary follows the Action module", "'infirmary': { attr: 'setting_dc_downtime'", "'infirmary': { attr: 'setting_dc_action'"],
  ["Sacred Nexus follows the Harm module", "'sacred nexus': { attr: 'setting_dc_downtime'", "'sacred nexus': { attr: 'setting_dc_harm'"],
  ["the healing text says +2 ticks", "'+1 tick to healing clock in downtime, in place of", "'+2 ticks to healing clock in downtime, in place of"],
  ["the healing text drops the book rule", "(Deep Cuts p88: \"+1d to healing rolls instead counts as 1 tick on the healing clock.\" The Deep Cuts", "(Deep Cuts p88. The Deep Cuts"],
  ["the claim card keeps the other text in full", "if (r.alt) { L.push(altButton(r.altLabel, 'claiminfo --c ' + cid + ' --n ' + s.slot)); }", "if (r.alt) { L.push(r.alt); L.push(altButton(r.altLabel, 'claiminfo --c ' + cid + ' --n ' + s.slot)); }"],
  ["the claim card has no button for the other text", "if (r.alt) { L.push(altButton(r.altLabel, 'claiminfo --c ' + cid + ' --n ' + s.slot)); }", "if (false) { L.push(altButton(r.altLabel, 'claiminfo --c ' + cid + ' --n ' + s.slot)); }"],
  ["the claim button posts the rule in force again", "postClaimCard(msg, t, s.held, s.name, [r.alt]);", "postClaimCard(msg, t, s.held, s.name, [r.main]);"],
  ["the Turf card keeps the other text in full", "L.push(altButton(tlabel, 'claiminfo --c ' + cid + ' --row turf'));", "L.push(talt); L.push(altButton(tlabel, 'claiminfo --c ' + cid + ' --row turf'));"],
  ["the Turf button posts the rule in force again", "postClaimCard(msg, t, held > 0, ttl, [talt]); return; }", "postClaimCard(msg, t, held > 0, ttl, [tmain]); return; }"],
  ["the upgrade card keeps the replaced sheet text", "altLabel = 'Show the sheet text it replaces'; sheetLine = ''; }", "altLabel = 'Show the sheet text it replaces'; }"],
  ["an upgrade button hides nothing new", "if (normName(u.text) === normName(dc.text)) { sheetLine = ''; }", "if (false) { sheetLine = ''; }"],
  ["the Deep Cuts text button has no label", "altLabel = 'Show the Deep Cuts text, module off';", "altLabel = '';"],
  ["the upgrade button posts the sheet text twice", "post([altLine]);", "post([altLine, altLine]);"],
  ["card formatting is off unless switched on", "return BUILD_HTML || !f || f[kind] !== false; }", "return BUILD_HTML || (!!f && f[kind] === true); }"],
  ["the held line is not bold", "L.push(bold(s.held ? 'Held by this crew.' : 'Not held by this crew.'));", "L.push(s.held ? 'Held by this crew.' : 'Not held by this crew.');"],
  ["the numbers in a rule are not bold", "function mech(x) { return fmtOn('bold') ? String(x).replace(", "function mech(x) { return false ? String(x).replace("],
  ["every number in a rule is bold", "var RE_MECH = /[+-]\\d+d?", "var RE_MECH = /\\d+d?"],
  ["source labels bold and rule labels italic", "return (source ? ital(label) : bold(label)) + ' ' + mech(text);", "return (source ? bold(label) : ital(label)) + ' ' + mech(text);"],
  ["asterisks in sheet text are kept", ".replace(/\\*/g, ASTERISK_OP);", ";"],
  ["a player can change the formatting", "if (!playerIsGM(msg.playerid)) { whisper(msg, 'BitDCrew: only the GM can change the card formatting.'); return; }", "if (false) { whisper(msg, 'BitDCrew: only the GM can change the card formatting.'); return; }"],
  ["fmt off leaves italic on", "f.bold = f.italic = (a === 'on');", "f.bold = (a === 'on');"],
  ["the probe has no bold line", "'Bold: **bold text**', ", ""],
  ["the cost is not bold", "bold(u.cost + ' coin')", "(u.cost + ' coin')"],
  ["the menu counts are not bold", "bold(clean(label) + ':') + ' '", "(clean(label) + ':') + ' '"],
  ["the claims legend is not italic", "ital(G_ON + ' held by the crew, ' + G_OFF + ' not held.')", "(G_ON + ' held by the crew, ' + G_OFF + ' not held.')"],
  ["the sheet text label is not italic", "ruleLine('On the sheet:', s.sheet, true)", "ruleLine('On the sheet:', s.sheet)"],
  ["the HTML card style is ignored", "if (cardMode() === 'html') {\n      var html = htmlCard(", "if (false) {\n      var html = htmlCard("],
  ["the HTML card does not escape <", ".replace(/</g, '&lt;')", ""],
  ["the HTML card does not escape &", ".replace(/&/g, '&amp;')", ""],
  ["the HTML card does not escape quotes", ".replace(/\"/g, '&quot;')", ""],
  ["the HTML card is whispered to the GM", "dbg('html card, ' + html.length + ' characters');\n      sendChat(SENDER, '/direct ' + html);", "dbg('html card, ' + html.length + ' characters');\n      sendChat(SENDER, '/w gm ' + html);"],
  ["the held badge is the wrong way round", "(m[1].charAt(0) === 'H' ? HC.held : HC.notheld)", "(m[1].charAt(0) === 'N' ? HC.held : HC.notheld)"],
  ["the rule in force is not a box", "(?:Rules in force|Rules \\(core book\\)|Also in force)", "(?:Rulez in force|Rules \\(core book\\)|Also in force)"],
  ["numbers in a rule are not gold", "htmlInline(m[2], HC.num)", "htmlInline(m[2], HC.bold)"],
  ["the button is not a link", "'<a href=\"$2\" style=\"'", "'<span title=\"$2\" style=\"'"],
  ["the HTML card does not say who showed it", "shown by ' + htmlEsc(by)", "' + htmlEsc(by)"],
  ["a styled card leaks into the next command", "    BUILD_HTML = false;\n    switch (o.verb) {", "    switch (o.verb) {"],
  ["probe2 does not send the public card", "      sendChat(SENDER, '/direct ' + html.replace('HTML TEST', 'HTML TEST (public, sent with /direct)'));\n", ""],
  ["the upgrade buttons put category and upgrade in one argument", "' --row ' + cat + ' --n ' + u.ref + ')';", "' --row ' + cat + ':' + u.ref + ')';"],
  ["the Special button uses the crew name", "return cat === 'special' ? crewTypeLabel(cid) + ' Special'", "return cat === 'special' ? getObj('character', cid).get('name') + ' Special'"],
  ["a crew with no type has no Special label", "|| 'Crew';", "|| '';"],
  ["Vault is not taken from the first box", "var UPGRADE_LEVELS = ['carriage', 'boat', 'secure', 'vault'];", "var UPGRADE_LEVELS = ['carriage', 'boat', 'secure'];"],
  ["every upgrade counts from the first box", "return (levels || n === boxes.length) ? 'taken' : 'partial';", "return 'taken';"],
  ["an upgrade needs every box including the two-box lair ones", "return (levels || n === boxes.length) ? 'taken' : 'partial';", "return n === boxes.length ? 'taken' : 'partial';"],
  ["Mastery has three boxes", "['mastery', 4]", "['mastery', 3]"],
  ["circles in reverse order", "return boxes.map(function (b) { return b ? G_ON : G_OFF; }).join('');", "return boxes.map(function (b) { return b ? G_ON : G_OFF; }).reverse().join('');"],
  ["the number of boxes on a special row is ignored", "n = clamp(getNum(cid, base + '_numboxes', 1), 1, 3), boxes", "n = 1, boxes"],
  ["blank special rows are listed", "var name = upgradeName(r.value);\n        if (!name) { return; }", "var name = upgradeName(r.value) || 'x';"],
  ["bracket text stays on the button", "return name.replace(/\\s*\\(.*$/, '').trim() || name;", "return name;"],
  ["the key prefix stays on the name", "claimDisplay(raw, /^crew upgrade /i)", "claimDisplay(raw)"],
  ["the count of taken includes in progress", "var taken = items.filter(function (u) { return u.state === 'taken'; }).length", "var taken = items.filter(function (u) { return u.state !== 'none'; }).length"],
  ["the in progress count is dropped", "(part ? ', ' + part + ' in progress' : '')", "''"],
  ["an unknown category is accepted", "if (UPGRADE_CATEGORIES.indexOf(cat) < 0) { whisper(msg, 'BitDCrew: unknown upgrade category.", "if (false) { whisper(msg, 'BitDCrew: unknown upgrade category."],
  ["a stale upgrade is accepted", ".filter(function (x) { return x.ref === ref; })[0];", ".filter(function (x) { return true; })[0];"],
  ["the Deep Cuts rule is in force for a core crew", "    if (dc && dtOn && dc.replaces) {", "    if (dc && dc.replaces) {"],
  ["the cost shows for a core crew", "if (dtOn && u.cost > 0) {", "if (u.cost > 0) {"],
  ["the cost total is missing", "(n > 1 ? ' (' + (u.cost * n) + ' coin for all ' + n + ' boxes)' : '')", "''"],
  ["the fixed upgrade cost is 5", "var UPGRADE_COIN_PER_BOX = 10;", "var UPGRADE_COIN_PER_BOX = 5;"],
  ["the sheet text copy is not used", "if (!text) { text = UPGRADE_SHEET_TEXT[key]; copy = true; }", "if (!text) { copy = true; }"],
  ["the copy is passed off as the sheet", "ruleLine(u.copy ? 'Sheet text (copy kept in the script):' : 'On the sheet:', u.text, true)", "ruleLine('On the sheet:', u.text, true)"],
  ["the specials get no book text", "var book = (cat === 'special' || cat === 'lair') ? upgradeBookText(u.name) : '', dc", "var book = cat === 'lair' ? upgradeBookText(u.name) : '', dc"],
  ["the Vehicle gets no book text", "var book = (cat === 'special' || cat === 'lair') ? upgradeBookText(u.name) : '', dc", "var book = cat === 'special' ? upgradeBookText(u.name) : '', dc"],
  ["the Quality rule is on every card", "if (cat === 'quality') { L.push(ruleLine('Core book, Quality:'", "if (true) { L.push(ruleLine('Core book, Quality:'"],
  ["an upgrade in progress is reported as taken", "u.state === 'partial' ? 'Upgrade in progress'", "u.state === 'partial' ? 'Upgrade taken'"],
  ["the upgrade card is whispered", "postRulesCard(msg, t, state, boxGlyphs(u.boxes) + ' ' + u.short, lines);", "whisper(msg, broadcast(t.c, { type: state, title: u.short, content: lines.join(NL) }));"],
  ["the category card is public", "whisper(msg, broadcast(t.c, { type: 'Crew upgrades', title: 'Show to the table'", "sendChat('player|' + msg.playerid, broadcast(t.c, { type: 'Crew upgrades', title: 'Show to the table'"],
  ["the lair legend loses its exceptions", "(cat === 'lair' ? ', except Carriage", "(false ? ', except Carriage"],
  ["Workshop replaces the sheet rule", "workshop: { page: 'p87', replaces: false", "workshop: { page: 'p87', replaces: true"],
  ["the Vault capacity is wrong", "the first holds 8 Coin, the second holds 12.", "the first holds 8 Coin, the second holds 16."],
  ["Mastery has no Deep Cuts line", "    mastery: { page: 'p88', replaces: true, text: UPGRADE_TRAINING_DC },\n", ""],
  ["the Hardened text is misquoted", "[['hardened', 'ordained'], 'Each PC gets +1 trauma box. This costs three upgrades", "[['hardened', 'ordained'], 'Each PC gets +1 trauma box. This costs two upgrades"],
  ["the Barge text is missing", "[['barge'], 'Add mobility to your lair. You can move it to a new location as a downtime activity.'],\n", ""],
  ["the Hawker apostrophe form is not matched", "[['hawker rigging', 'hawkers rigging'],", "[['hawker rigging'],"],
  ["the ampersand in Underground maps is not matched", ".replace(/&/g, 'and').replace(/'/g, '')", ".replace(/'/g, '')"],
  ["the Smuggler apostrophe form is not matched", "[['smuggler rigging', 'smugglers rigging'],", "[['smuggler rigging'],"],
  ["a typo in a sheet text copy", "insight: 'Earn 2 xp when training insight during downtime.'", "insight: 'Earn 3 xp when training insight during downtime.'"],
  ["Elite Rooks text names the wrong type", "[['elite rooks'], 'All of your cohorts with the Rooks type get +1d to quality rolls for Rook-related actions.'],", "[['elite rooks'], 'All of your cohorts with the Rovers type get +1d to quality rolls for Rook-related actions.'],"],
  ["a claim text is misquoted", "helps deflect some of the heat from law enforcement.'],", "helps deflect some of the heat from the law.'],"],
  ["a claim has no book text", "    'fleet': [[['smugglers'],", "    'fleets': [[['smugglers'],"],
  ['non-ASCII character in the source', "var NL = '\\n';", "var NL = '\\n'; var X = 'é';"]
];

let survived = 0, notApplied = 0, killed = 0;
M.forEach((m) => {
  const n = SRC.split(m[1]).length - 1;
  if (n !== 1) { notApplied++; console.log('NOT APPLIED (' + n + ' matches):', m[0]); return; }
  const file = path.join(os.tmpdir(), 'crew_mut_' + process.pid + '.js');
  fs.writeFileSync(file, SRC.replace(m[1], () => m[2]));
  const r = cp.spawnSync('node', [TEST, file, TRANS, PC], { encoding: 'utf8' });
  fs.unlinkSync(file);
  if (r.status === 0) { survived++; console.log('SURVIVED:', m[0]); }
  else { killed++; const first = (r.stdout.split('\n').find(l => /^FAIL:/.test(l)) || (r.stderr.split('\n')[0] || 'crashed')).slice(0, 110); console.log('killed  : ' + m[0] + '  <- ' + first); }
});
console.log(M.length + ' mutations: ' + killed + ' caught, ' + survived + ' survived, ' + notApplied + ' not applied');
process.exit(survived || notApplied ? 1 : 0);
