// Breaks "BitD Crew Token Action Maker.js" in many small ways, one at a time, and checks that crew_mock_test.js fails each time.
// Usage: node crew_mutation_check.js <crew script> <translation.json> <PC script>
// A mutation that is not applied (its text is missing or ambiguous) or that survives (tests still pass) is a failure.
const fs = require('fs');
const os = require('os');
const path = require('path');
const cp = require('child_process');

const SCRIPT = process.argv[2], TRANS = process.argv[3], PC = process.argv[4];
if (!SCRIPT || !TRANS || !PC) { console.log('usage: node crew_mutation_check.js <crew script> <translation.json> <PC script>'); process.exit(2); }
const SRC = fs.readFileSync(SCRIPT, 'utf8');
const TEST = path.join(__dirname, 'crew_mock_test.js');

const M = [
  ['Heat track of 10', "var HEAT_MAX = 9, REP_MAX = 12", "var HEAT_MAX = 10, REP_MAX = 12"],
  ['Heat fills at 10 not 9', "while (total >= HEAT_MAX) {", "while (total > HEAT_MAX) {"],
  ['Wanted not capped', "if (wanted < w.max) { wanted++; } else { capped++; }", "wanted++;"],
  ['crew Tier left out of score Heat', "var total = base + tier + target1 + chaos + death + wit,", "var total = base + target1 + chaos + death + wit,"],
  ['Rep 1 per 3 Heat', "Math.floor(total / 2) + Math.max(0, tTier - tier)", "Math.floor(total / 3) + Math.max(0, tTier - tier)"],
  ['payoff 2 x target Tier', "var payoff = pcs + 3 * tTier;", "var payoff = pcs + 2 * tTier;"],
  ['tithe 1 per 5', "flow.tier <= 2 ? Math.floor(flow.earned / 4) : 0", "flow.tier <= 2 ? Math.floor(flow.earned / 5) : 0"],
  ['tithe up to Tier 3', "flow.tier <= 2 ? Math.floor(flow.earned / 4) : 0", "flow.tier <= 3 ? Math.floor(flow.earned / 4) : 0"],
  ['crew gate points at characters', "getAttr(ch.id, 'sheet_type', 'character') !== 'crew'", "getAttr(ch.id, 'sheet_type', 'character') !== 'character'"],
  ['crew auto rule fires on any sheet', "if (!ch || getAttr(cid, 'sheet_type', 'character') !== 'crew') { return; }", "if (!ch) { return; }"],
  ['anyone may use any crew', "return cb.indexOf('all') >= 0 || cb.indexOf(msg.playerid) >= 0;", "return true;"],
  ['command shared with the PC script', "var CMD = '!bitdcrew';", "var CMD = '!bitd';"],
  ['ability marker shared with the PC script', "var MARK = 'bitd-crew-tam';", "var MARK = 'bitd-tam';"],
  ['macro name shared with the PC script', "var MACRO_NAME = 'CREW_TAM';", "var MACRO_NAME = 'BLADES_TAM';"],
  ['state key shared with the PC script', "var STATE_KEY = 'BitDCrewTAM';", "var STATE_KEY = 'BitDTAM';"],
  ['entanglement table cell wrong', "['Reprisals', 'Unquiet Dead']", "['Reprisals', 'Rivals']"],
  ['entanglement Heat 6 column starts at 7', "w.heat >= 6 ? 2 : (w.heat >= 4 ? 1 : 0)", "w.heat >= 7 ? 2 : (w.heat >= 4 ? 1 : 0)"],
  ['entanglement zero dice take the highest', "lowest: pool <= 0", "lowest: false"],
  ['Downtime coin written to the standard track', "return mods(cid).downtime ? { attr: 'crewcoin_dc', max: 24 }", "return mods(cid).downtime ? { attr: 'crewcoin', max: 24 }"],
  ['vault holds 6', "4 + (v1 ? 8 : 0) + (v2 ? 12 : 0)", "4 + (v1 ? 6 : 0) + (v2 ? 12 : 0)"],
  ['hold strong only above Tier', "getNum(cid, 'turf', 0) >= getNum(cid, 'crew_tier', 0) ? 'strong' : 'weak'", "getNum(cid, 'turf', 0) > getNum(cid, 'crew_tier', 0) ? 'strong' : 'weak'"],
  ['5th Wanted box reads the wrong attribute', "{ attr: 'wantedDC', max: 5, label", "{ attr: 'wanted', max: 5, label"],
  ['a callback on the Tier roll', "'{{title=^{crew_tier}}} {{subtitle=^{roll_their}}} {{' + diceField(pool) + '}}' + tail(cid, t.c);\n      sendChat('player|' + msg.playerid, text);", "'{{title=^{crew_tier}}} {{subtitle=^{roll_their}}} {{' + diceField(pool) + '}}' + tail(cid, t.c);\n      sendChat('player|' + msg.playerid, text, function () {});"],
  ['bar 1 max of 12', "bar1_max: HEAT_MAX", "bar1_max: 12"],
  ['bar 1 not linked to heat', "tok.set({ bar1_link: a.id });", "tok.set({ bar2_link: a.id });"],
  ['Slippery does nothing', "Math.max(0, actual - 1)", "actual"],
  ['core advancement reminder with Downtime on', "before + 1 >= CREW_XP_MAX && !m.downtime", "before + 1 >= CREW_XP_MAX"],
  ['No Traces takes 2', "total -= 1; parts.push('No Traces -1');", "total -= 2; parts.push('No Traces -1');"],
  ['payoff steps can repeat', "flow.done[step] = true;\n    return flow;", "return flow;"],
  ['Incarceration keeps Heat', "setAttr(cid, 'heat', 0);\n        syncHeatBars(cid);", "syncHeatBars(cid);"],
  ['fencing Heat 1 per 2 Coin', "Math.floor(coins[code] / 4)", "Math.floor(coins[code] / 2)"],
  ['bonus dice not limited', "bonus = clamp(bonus, -3, 6);", ""],
  ['cohort ignores elite or expert', "((cohortType(cid, prefix) === 'elite' || cohortType(cid, prefix) === 'expert') ? 1 : 0)", "0"],
  ['impaired adds a die', "- getNum(cid, prefix + '_impaired', 0) +", "+ getNum(cid, prefix + '_impaired', 0) +"],
  ['Wanted level gained on Heat 8', "var res = applyHeat(cid, cur, 0);", "var res = applyHeat(cid, cur + 1, 0);"],
  ['Downtime crew can roll Entanglement', "if (m.downtime) {\n        whisper(msg, 'BitDCrew: Deep Cuts Downtime has no entanglement roll.", "if (false) {\n        whisper(msg, 'BitDCrew: Deep Cuts Downtime has no entanglement roll."],
  ['deposit ignores vault room', "Math.max(0, Math.min(coinCapacity(cid), tr.max) - cur)", "Math.max(0, tr.max - cur)"],
  ['half deposit rounds up', "(code === 'half' ? Math.floor(flow.net / 2) : 0)", "(code === 'half' ? Math.ceil(flow.net / 2) : 0)"],
  ['abilities menu lists unticked', "if (String(getAttrByName(cid, 'repeating_crewability_' + r.row + '_check')) !== '1') { return; }", ""],
  ['clock may pass its size', "var next = clamp(k.progress + (delta > 0 ? 1 : -1), 0, k.size);", "var next = clamp(k.progress + (delta > 0 ? 1 : -1), 0, 99);"],
  ["Reduce Heat takes 2", "    var res = addHeat(cid, -1);\n    note(msg, t.c, 'Heat', 'Heat ' + res.after", "    var res = addHeat(cid, -2);\n    note(msg, t.c, 'Heat', 'Heat ' + res.after"],
  ["Rep not capped at 12", "Math.min(REP_MAX, before + want)", "before + want"],
  ["Leverage on a gain of 0", "(!noLeverage && n > 0 && crewAbilityOn(cid, 'Leverage')) ? 1 : 0", "(!noLeverage && crewAbilityOn(cid, 'Leverage')) ? 1 : 0"],
  ["Leverage gives +2", "(!noLeverage && n > 0 && crewAbilityOn(cid, 'Leverage')) ? 1 : 0", "(!noLeverage && n > 0 && crewAbilityOn(cid, 'Leverage')) ? 2 : 0"],
  ["Misdirection gives up the larger half", "give = Math.floor(earned / 2);", "give = Math.ceil(earned / 2);"],
  ["Misdirection halves the Rep that fit, not the Rep earned", "give = Math.floor(earned / 2);", "give = Math.floor(rg.applied / 2);"],
  ["Misdirection halves the Rep asked, not earned (no Leverage)", "var earned = repGain + rg.bonus,", "var earned = repGain,"],
  ["Misdirection offered at an earn of 1", "      if (give >= 1) {\n        L.push('Misdirection: you may give up", "      if (give >= 0) {\n        L.push('Misdirection: you may give up"],
  ["Misdirection offered without the ability", "    if (crewAbilityOn(cid, 'Misdirection')) {\n      if (give >= 1) {", "    if (crewAbilityOn(cid, 'Misdirection') || crewAbilityListed(cid, 'Misdirection')) {\n      if (give >= 1) {"],
  ["Misdirection withheld in silence (no reason)", "        L.push('Misdirection is not offered: half of the Rep earned (' + earned + '), rounded down, is 0.');\n", ""],
  ["unticked Misdirection says nothing", "    } else if (crewAbilityListed(cid, 'Misdirection')) {", "    } else if (false) {"],
  ["crews without Misdirection are told about it", "    } else if (crewAbilityListed(cid, 'Misdirection')) {", "    } else if (true) {"],
  ["Score recorded never mentions Rep that did not fit", "flow.repFit !== undefined && flow.repFit < flow.repGain ?", "false ?"],
  ["Score recorded always mentions fit", "flow.repFit !== undefined && flow.repFit < flow.repGain ?", "flow.repFit !== undefined ?"],
  ["core Score card forgets to name the rule set", "'Downtime module off: this is the core Score, Heat only. Rep and the Payoff are not tracked.'", "'Core Score.'"],
  ["No Traces Rep at End Downtime with Heat 1", "      if (heat === 0) {\n        r = gainRep(cid, 1);", "      if (heat <= 1) {\n        r = gainRep(cid, 1);"],
  ["No Traces gives 2 Rep at End Downtime", "r = gainRep(cid, 1);", "r = gainRep(cid, 2);"],
  ["End Downtime leaves the Downtime open", "    d.ended = true;\n    L.push(d.startHeat", "    d.ended = false;\n    L.push(d.startHeat"],
  ["Just Passing Through takes 2 Heat", "res = addHeat(cid, -1);\n        d.log.push('Just Passing Through", "res = addHeat(cid, -2);\n        d.log.push('Just Passing Through"],
  ["Just Passing Through not once per Downtime", "        d.used.jpt = true;\n", ""],
  ["Just Passing Through spent at Heat 0", "if (getNum(cid, 'heat', 0) < 1) { note(msg, t.c, 'Heat', 'Heat 0', 'There is no Heat to reduce, so", "if (false) { note(msg, t.c, 'Heat', 'Heat 0', 'There is no Heat to reduce, so"],
  ["Just Passing Through button at Heat 0", "ab['just passing through'] === true && !d.used.jpt && heat > 0", "ab['just passing through'] === true && !d.used.jpt"],
  ["Reduce Heat buttons at Heat 0", "    if (heat > 0) {\n      L.push('Reduce Heat by 1", "    if (true) {\n      L.push('Reduce Heat by 1"],
  ["Downtime id not checked", "if (!d || !o.idx || d.id !== o.idx) {", "if (!d) {"],
  ["Heat and Hold on a crew without Downtime", "    if (!mods(cid).downtime) { whisper(msg, 'BitDCrew: Heat and Hold is a Deep Cuts Downtime step, and the module is off for this crew.'); return; }\n    var d = openDowntime(cid);", "    var d = openDowntime(cid);"],
  ["Score does not start a Downtime", "    startDowntime(cid, 'score');\n", ""],
  ["no Heat and Hold card after the deposit", "    var dd = openDowntime(cid);\n    if (dd) {", "    var dd = null;\n    if (dd) {"],
  ["an ended Downtime still counts as open", "return (d && !d.ended) ? d : null;", "return d || null;"],
  ["a new Downtime keeps the old used list", "used: {}, pending: {}, log: [], ended: false", "used: (prev ? prev.used : {}), pending: {}, log: [], ended: false"],
  ["party tag wrong", "var PARTY_TAG = '_roll20_internal_party_tag_';", "var PARTY_TAG = '_roll20_party_';"],
  ["party flag read from arrays only", "(typeof t === 'string' ? t : JSON.stringify(t)).indexOf(PARTY_TAG) >= 0;", "(typeof t === 'string' ? '' : JSON.stringify(t)).indexOf(PARTY_TAG) >= 0;"],
  ["party count includes crews", "return partyCharacters().filter(function (c) { return getAttr(c.id, 'sheet_type', 'character') === 'character'; }).length;", "return partyCharacters().length;"],
  ["empty party still scores", "if (pn < 1) {", "if (pn < 0) {"],
  ["party probe open to players", "    if (!playerIsGM(msg.playerid)) { whisper(msg, 'BitDCrew: only the GM can run the party check.'); return; }\n", ""],
  ["debug always on", "function dbg(text) { if (botState().debug) {", "function dbg(text) { if (true) {"],
  ["debug switch open to players", "    if (!playerIsGM(msg.playerid)) { whisper(msg, 'BitDCrew: only the GM can change debug logging.'); return; }\n", ""],
  ["Payoff prompt without the party option", "' ?{PCs for the Payoff (1 Coin each)|All party members,party|'", "' ?{PCs for the Payoff (1 Coin each)|'"],
  ["Downtime state not created", "    state[STATE_KEY].downtime = state[STATE_KEY].downtime || {};\n", ""],
  ["Status says Just Passing Through is active at Heat 5", "(heat <= 4 ? 'active now'", "(heat <= 5 ? 'active now'"],
  ["Engagement without the die for luck", "pool = 1 + net, parts = ['1 luck'];", "pool = net, parts = ['1 luck'];"],
  ["Engagement bonus counts double", "pool += 1; parts.push('+1 ' + name)", "pool += 2; parts.push('+1 ' + name)"],
  ["Door Kickers on stealth too", "name: 'Door Kickers', plans: ['assault'] }", "name: 'Door Kickers', plans: ['assault', 'stealth'] }"],
  ["Second Story on assault too", "name: 'Second Story', plans: ['stealth'] }", "name: 'Second Story', plans: ['stealth', 'assault'] }"],
  ["Predators on stealth only", "plans: ['stealth', 'deception'], murder: true }", "plans: ['stealth'], murder: true }"],
  ["Predators without a murder goal", "plans: ['stealth', 'deception'], murder: true }", "plans: ['stealth', 'deception'], murder: false }"],
  ["Deadly Focus (River) is automated", "return crewAbilityListed(cid, 'Predators'); }", "return crewAbilityListed(cid, 'Predators') || crewAbilityListed(cid, 'Deadly Focus'); }"],
  ["Cover Identities follows the sheet (transport)", "name: 'Cover Identities', plans: ['deception', 'social'] }", "name: 'Cover Identities', plans: ['deception', 'transport'] }"],
  ["The Governor (River) is automated", "{ kind: 'claim', name: 'Secret Routes', plans: ['transport'] }\n  ];", "{ kind: 'claim', name: 'Secret Routes', plans: ['transport'] },\n    { kind: 'claim', name: 'The Governor', plans: PLAN_TYPES }\n  ];"],
  ["unticked claims count", "if (!isOn(cid, 'claim_' + i + '_check')) { continue; }\n      var nm = normName(getAttrByName(cid, 'claim_' + i + '_name')).replace(/_/g, ' ').replace(/^claim /, '');\n      if (nm) { on[nm] = true; }", "if (false) { continue; }\n      var nm = normName(getAttrByName(cid, 'claim_' + i + '_name')).replace(/_/g, ' ').replace(/^claim /, '');\n      if (nm) { on[nm] = true; }"],
  ["unticked income claims count", "if (!isOn(cid, 'claim_' + i + '_check')) { continue; }\n      var nm = normName(getAttrByName(cid, 'claim_' + i + '_name')).replace(/_/g, ' ').replace(/^claim /, '');\n      CLAIM_INCOME", "if (false) { continue; }\n      var nm = normName(getAttrByName(cid, 'claim_' + i + '_name')).replace(/_/g, ' ').replace(/^claim /, '');\n      CLAIM_INCOME"],
  ["claim key prefix not removed", ".replace(/_/g, ' ').replace(/^claim /, '');\n      if (nm) { on[nm] = true; }", ".replace(/_/g, ' ');\n      if (nm) { on[nm] = true; }"],
  ["income claim key prefix not removed", ".replace(/_/g, ' ').replace(/^claim /, '');\n      CLAIM_INCOME", ".replace(/_/g, ' ');\n      CLAIM_INCOME"],
  ["transport is not a plan type", "'occult', 'social', 'transport'];\n  var ENG_SOURCES", "'occult', 'social'];\n  var ENG_SOURCES"],
  ["net dice range 9", "net < -4 || net > 4", "net < -9 || net > 9"],
  ["zero pool says nothing", "(pool <= 0 ? ' (no dice: roll 2d and keep the lowest)' : '')", "''"],
  ["murder prompt never asked", "return crewAbilityListed(cid, 'Predators'); }", "return false; }"],
  ["stale Engagement macro accepted", "if (o.pos.length !== want) {", "if (false) {"],
  ["Engagement card is not an engagement card", "{{subtitle=^{roll_for}}} {{title-engagement=1}} {{title=^{engagement}}} {{'", "{{subtitle=^{roll_for}}} {{title-fortune=1}} {{title=^{engagement}}} {{'"],
  ["net dice default is not 0", "|0|1|2|3|4|-1|-2|-3|-4}", "|1|0|2|3|4|-1|-2|-3|-4}"],
  ["Zealotry reminder missing", "['Zealotry', 'Zealotry: your cohorts", "['Zealotri', 'Zealotry: your cohorts"],
  ["reminders shown for unticked abilities", "if (on[normName(r[0])] === true) { L.push(r[1]); }", "if (true) { L.push(r[1]); }"],
  ["Edge limit 999", "EDGE_MAX = 99;", "EDGE_MAX = 999;"],
  ["Begin score offered without the Action module", "(m.action ? '|Begin score: Edge", "(true ? '|Begin score: Edge"],
  ["Begin score ignores the Action module", "if (!mods(cid).action) { whisper(msg, 'BitDCrew: Edge comes from", "if (false) { whisper(msg, 'BitDCrew: Edge comes from"],
  ["Begin score ignores the ability", "if (!crewAbilityOn(cid, 'Bound in Darkness')) {", "if (false) {"],
  ["Begin score with an empty party", "    if (!pcs.length) {\n      whisper(msg, 'BitDCrew: no player characters are marked as Party members, so there is nobody", "    if (false) {\n      whisper(msg, 'BitDCrew: no player characters are marked as Party members, so there is nobody"],
  ["party PCs include crew sheets", "=== 'character'; });\n  }\n  function edgeOf", "=== 'character' || true; });\n  }\n  function edgeOf"],
  ["Edge goes to every character", "    var pcs = partyPcs();\n    if (code === 'all') {", "    var pcs = findObjs({ _type: 'character' });\n    if (code === 'all') {"],
  ["All gives 2 Edge", "var before = edgeOf(pc.id), after = setEdgeOf(pc.id, before + 1);\n        L.push(btn(pc.get('name')) + ' Edge ' + before", "var before = edgeOf(pc.id), after = setEdgeOf(pc.id, before + 2);\n        L.push(btn(pc.get('name')) + ' Edge ' + before"],
  ["All ignores who already got Edge", "if (flow.done[step]) { return; }", "if (false) { return; }"],
  ["a PC button works more than once", "if (flow.done[step1]) {", "if (false) {"],
  ["Edge token bar not set", "    setAttr(pcId, EDGE_ATTR, n);\n    syncEdgeBars(pcId);\n", "    setAttr(pcId, EDGE_ATTR, n);\n"],
  ["Clear Edge clears nothing", "if (had > 0) { setEdgeOf(pc.id, 0);", "if (had > 0) {"],
  ["Clear Edge offered when nobody has Edge", "        if (holders.length) {", "        if (true) {"],
  ["Clear Edge works more than once", "flowFor(msg, t, o, 'edgeclear')", "flowFor(msg, t, o, 'edgeclear' + Date.now() + Math.random())"],
  ["Edge line on a crew without the Action module", "    if (mods(cid).action) {\n      var pcs0", "    if (true) {\n      var pcs0"],
  ["Begin score card accepts any flow", "flow.cid !== cid || flow.kind !== 'edge')", "flow.cid !== cid)"],
  ["Heat claim takes 3", "var HEAT_CLAIM = 2;", "var HEAT_CLAIM = 3;"],
  ["Heat claim can push Heat below 0", "if (total < 0) { total = 0; parts.push('not below 0'); }", "if (total < 0) { parts.push('not below 0'); }"],
  ["Heat claim applied to a total of 0", "    if (total < 1) { return total; }\n    var cl = claimsOn(cid);", "    if (total < 0) { return total; }\n    var cl = claimsOn(cid);"],
  ["core Score ignores Heat claims", "    total = applyHeatClaims(cid, total, parts);\n    var res = addHeat(cid, total);\n    var L = ['Heat +' + total", "    var res = addHeat(cid, total);\n    var L = ['Heat +' + total"],
  ["Deep Cuts Score ignores Heat claims", "    total = applyHeatClaims(cid, total, parts);\n    var res = addHeat(cid, total);\n    L.push(", "    var res = addHeat(cid, total);\n    L.push("],
  ["Rep from the Heat before the claim", "Math.floor(total / 2) + Math.max(0, tTier - tier) + (vt ? 1 : 0)", "Math.floor((total + 2) / 2) + Math.max(0, tTier - tier) + (vt ? 1 : 0)"],
  ["Victim Trophies gives 2", "+ (vt ? 1 : 0), rg = gainRep(cid, repGain)", "+ (vt ? 2 : 0), rg = gainRep(cid, repGain)"],
  ["Victim Trophies ignored", "var vt = claimHas(claimsOn(cid), [CLAIM_REP_AUTO]);", "var vt = false;"],
  ["claim Rep boosted by Leverage", "var rg = gainRep(cid, def.rep, true);", "var rg = gainRep(cid, def.rep);"],
  ["Publicity gives 3", "{ name: 'Publicity', label: 'takedown score', rep: 2 }", "{ name: 'Publicity', label: 'takedown score', rep: 3 }"],
  ["claim button works more than once", "var flow = flowFor(msg, t, o, code); if (!flow) { return; }\n    if (m[1] === 'rep') {", "var flow = flowFor(msg, t, o, code + Math.random()); if (!flow) { return; }\n    if (m[1] === 'rep') {"],
  ["Coin claim gives 3", "flow.base += 2;", "flow.base += 3;"],
  ["Coin claim after the seized step", "if (pre && pre.cid === cid && m[1] === 'coin' && pre.done.seized) {", "if (false) {"],
  ["unticked claim button accepted", "if (!claimHas(claimsOn(cid), names)) { whisper(msg, 'BitDCrew: ' + label", "if (false) { whisper(msg, 'BitDCrew: ' + label"],
  ["Rep claim buttons for claims not ticked", "if (claimHas(cl2, [c.name])) { claimBtns.push", "if (true) { claimBtns.push"],
  ["Surplus Cache spelling missing", "names: ['Surplus Caches', 'Surplus Cache']", "names: ['Surplus Caches']"],
  ["income rolls Tier plus 1", "diceField(tier) + '}} {{notes='", "diceField(tier + 1) + '}} {{notes='"],
  ["income is the die, not die minus Heat", "var coin = Math.max(0, die - w.heat);", "var coin = die;"],
  ["income can go negative", "var coin = Math.max(0, die - w.heat);", "var coin = die - w.heat;"],
  ["income reads Heat after the roll", "var coin = Math.max(0, die - w.heat);", "var coin = Math.max(0, die - getNum(w.cid, 'heat', 0));"],
  ["income claim rolls more than once", "if (d.used['inc' + slot]) { note(", "if (false) { note("],
  ["income is added more than once", "if (d.used['incpay' + ps]) {", "if (false) {"],
  ["income ignores vault room", "put = Math.min(pend, iroom);", "put = pend;"],
  ["income button adds nothing", "if (put > 0) { setAttr(cid, itr.attr, icur + put); }", "if (put > 0) { }"],
  ["Info Biz counted as income", "'Protection Racket', 'Side Business'];", "'Protection Racket', 'Side Business', 'Info Biz'];"],
  ["income claims missing from Heat and Hold", "    var inc = incomeClaims(cid);\n    if (inc.length) {", "    var inc = incomeClaims(cid);\n    if (false) {"],
  ["unread income roll is silent", "if (watching.indexOf(w) < 0) { return; }\n      watching.splice", "return;\n      watching.splice"],
  ["Status hides the claims", "if (cip.length) { L.push('Claims the script counts: '", "if (false) { L.push('Claims the script counts: '"],
  ["core crews list Deep Cuts claims", "    if (dt) {\n      if (claimHas(cl, [CLAIM_REP_AUTO]))", "    if (true) {\n      if (claimHas(cl, [CLAIM_REP_AUTO]))"],
  ["Engagement arithmetic card missing", "    sendChat('player|' + msg.playerid, broadcast(t.c, { type: 'Engagement', title: Math.max(pool, 0) + 'd', content: clean(line) }));\n", ""],
  ["Engagement arithmetic put back on the unreadable notes line", "{{' + diceField(pool) + '}}' +\n      tail(cid, t.c));", "{{' + diceField(pool) + '}} {{notes=' + clean(line) + '}}' +\n      tail(cid, t.c));"],
  ['non-ASCII character in the source', "var NL = '\\n';", "var NL = '\\n'; var X = 'é';"]
];

let survived = 0, notApplied = 0, killed = 0;
M.forEach((m) => {
  const n = SRC.split(m[1]).length - 1;
  if (n !== 1) { notApplied++; console.log('NOT APPLIED (' + n + ' matches):', m[0]); return; }
  const file = path.join(os.tmpdir(), 'crew_mut_' + process.pid + '.js');
  fs.writeFileSync(file, SRC.replace(m[1], () => m[2]));
  const r = cp.spawnSync('node', [TEST, file, TRANS, PC], { encoding: 'utf8' });
  fs.unlinkSync(file);
  if (r.status === 0) { survived++; console.log('SURVIVED:', m[0]); }
  else { killed++; const first = (r.stdout.split('\n').find(l => /^FAIL:/.test(l)) || (r.stderr.split('\n')[0] || 'crashed')).slice(0, 110); console.log('killed  : ' + m[0] + '  <- ' + first); }
});
console.log(M.length + ' mutations: ' + killed + ' caught, ' + survived + ' survived, ' + notApplied + ' not applied');
process.exit(survived || notApplied ? 1 : 0);
